sudo: required
dist: trusty

language: c

compiler:
  - gcc
  - clang

install:
  # build essentials
  - sudo apt-get install -y build-essential fakeroot debhelper
  - sudo apt-get install -y make libtool liblua5.1-0-dev

script:
  # Build the package.
  - (cd pkg && make deb)
  # Compile and run the tests.
  - cd src && make tests

matrix:
  include:
    - before_script:
        - sudo apt-get install -y openjdk-8-jre-headless openjdk-8-jdk-headless
        - cd src && make tests
      script:
        - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        - cd ${TRAVIS_BUILD_DIR}/src && make tests
        - ls -la ${TRAVIS_BUILD_DIR}/src
        - cd ${TRAVIS_BUILD_DIR}/src/jni && make test
